# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2018.2.4\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2018.2.4\bin\cmake\win\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\hunte\Desktop\Data Structures Homework\Final Project - final ver"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\hunte\Desktop\Data Structures Homework\Final Project - final ver\cmake-build-debug"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files\JetBrains\CLion 2018.2.4\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\JetBrains\CLion 2018.2.4\bin\cmake\win\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\hunte\Desktop\Data Structures Homework\Final Project - final ver\cmake-build-debug\CMakeFiles" "C:\Users\hunte\Desktop\Data Structures Homework\Final Project - final ver\cmake-build-debug\CMakeFiles\progress.marks"
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\hunte\Desktop\Data Structures Homework\Final Project - final ver\cmake-build-debug\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Final_Project___final_ver

# Build rule for target.
Final_Project___final_ver: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 Final_Project___final_ver
.PHONY : Final_Project___final_ver

# fast build rule for target.
Final_Project___final_ver/fast:
	$(MAKE) -f CMakeFiles\Final_Project___final_ver.dir\build.make CMakeFiles/Final_Project___final_ver.dir/build
.PHONY : Final_Project___final_ver/fast

Actor.obj: Actor.cpp.obj

.PHONY : Actor.obj

# target to build an object file
Actor.cpp.obj:
	$(MAKE) -f CMakeFiles\Final_Project___final_ver.dir\build.make CMakeFiles/Final_Project___final_ver.dir/Actor.cpp.obj
.PHONY : Actor.cpp.obj

Actor.i: Actor.cpp.i

.PHONY : Actor.i

# target to preprocess a source file
Actor.cpp.i:
	$(MAKE) -f CMakeFiles\Final_Project___final_ver.dir\build.make CMakeFiles/Final_Project___final_ver.dir/Actor.cpp.i
.PHONY : Actor.cpp.i

Actor.s: Actor.cpp.s

.PHONY : Actor.s

# target to generate assembly for a file
Actor.cpp.s:
	$(MAKE) -f CMakeFiles\Final_Project___final_ver.dir\build.make CMakeFiles/Final_Project___final_ver.dir/Actor.cpp.s
.PHONY : Actor.cpp.s

CullerFP.obj: CullerFP.cpp.obj

.PHONY : CullerFP.obj

# target to build an object file
CullerFP.cpp.obj:
	$(MAKE) -f CMakeFiles\Final_Project___final_ver.dir\build.make CMakeFiles/Final_Project___final_ver.dir/CullerFP.cpp.obj
.PHONY : CullerFP.cpp.obj

CullerFP.i: CullerFP.cpp.i

.PHONY : CullerFP.i

# target to preprocess a source file
CullerFP.cpp.i:
	$(MAKE) -f CMakeFiles\Final_Project___final_ver.dir\build.make CMakeFiles/Final_Project___final_ver.dir/CullerFP.cpp.i
.PHONY : CullerFP.cpp.i

CullerFP.s: CullerFP.cpp.s

.PHONY : CullerFP.s

# target to generate assembly for a file
CullerFP.cpp.s:
	$(MAKE) -f CMakeFiles\Final_Project___final_ver.dir\build.make CMakeFiles/Final_Project___final_ver.dir/CullerFP.cpp.s
.PHONY : CullerFP.cpp.s

Menu.obj: Menu.cpp.obj

.PHONY : Menu.obj

# target to build an object file
Menu.cpp.obj:
	$(MAKE) -f CMakeFiles\Final_Project___final_ver.dir\build.make CMakeFiles/Final_Project___final_ver.dir/Menu.cpp.obj
.PHONY : Menu.cpp.obj

Menu.i: Menu.cpp.i

.PHONY : Menu.i

# target to preprocess a source file
Menu.cpp.i:
	$(MAKE) -f CMakeFiles\Final_Project___final_ver.dir\build.make CMakeFiles/Final_Project___final_ver.dir/Menu.cpp.i
.PHONY : Menu.cpp.i

Menu.s: Menu.cpp.s

.PHONY : Menu.s

# target to generate assembly for a file
Menu.cpp.s:
	$(MAKE) -f CMakeFiles\Final_Project___final_ver.dir\build.make CMakeFiles/Final_Project___final_ver.dir/Menu.cpp.s
.PHONY : Menu.cpp.s

Picture.obj: Picture.cpp.obj

.PHONY : Picture.obj

# target to build an object file
Picture.cpp.obj:
	$(MAKE) -f CMakeFiles\Final_Project___final_ver.dir\build.make CMakeFiles/Final_Project___final_ver.dir/Picture.cpp.obj
.PHONY : Picture.cpp.obj

Picture.i: Picture.cpp.i

.PHONY : Picture.i

# target to preprocess a source file
Picture.cpp.i:
	$(MAKE) -f CMakeFiles\Final_Project___final_ver.dir\build.make CMakeFiles/Final_Project___final_ver.dir/Picture.cpp.i
.PHONY : Picture.cpp.i

Picture.s: Picture.cpp.s

.PHONY : Picture.s

# target to generate assembly for a file
Picture.cpp.s:
	$(MAKE) -f CMakeFiles\Final_Project___final_ver.dir\build.make CMakeFiles/Final_Project___final_ver.dir/Picture.cpp.s
.PHONY : Picture.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... Final_Project___final_ver
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Actor.obj
	@echo ... Actor.i
	@echo ... Actor.s
	@echo ... CullerFP.obj
	@echo ... CullerFP.i
	@echo ... CullerFP.s
	@echo ... Menu.obj
	@echo ... Menu.i
	@echo ... Menu.s
	@echo ... Picture.obj
	@echo ... Picture.i
	@echo ... Picture.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

